name: Build OKHTTP
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    
permissions:
  contents: read

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  Build_OKHTTP:
    permissions:
      checks: write # for actions/upload-artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build OKHTTP
        run: |
          cd "$GITHUB_WORKSPACE"
          git clone https://github.com/square/okhttp -b parent-4.1.0
          cd okhttp 
          ./gradlew build
         

      - name: Upload OKHTTP
        uses: actions/upload-artifact@v4
        with:
          name: OKHTTP
          path: okhttp/*
